#!/bin/bash

set -e
set -u

VERSION=0
OUT_SUFFIX='_labeled'

DEFAULT_LABEL='www.coolparadox.com'
DEFAULT_FONT='Arial'

# Parse command line arguments

ME=$( basename "$0" )

USAGE_LINE="${ME} [-h | --help | OPTIONS] [<input file>]"

usage() {

	echo "usage: $USAGE_LINE" 1>&2
	exit 1

}

help() {

	cat <<-__eod__
		$USAGE_LINE

		Labels an image at the bottom with a textual line.

		Options:
		  -h, --help          This help text.
		  -l, --label LABEL   Text label to be used for labeling.
		  -o, --output FILE   Output file.
		  -v, --version       Version information.

		Output file name is the same as input with '${OUT_SUFFIX}' appended.
		If input file is '-' or absent, reads from stdin and writes to stdout.
		If output file is '-', writes to stdout.

		LABEL defaults to '$DEFAULT_LABEL'.

		This script requires ImageMagick <www.imagemagick.org> tools.

		Please file bug reports to:
		http://github.com/coolparadox/watermark/issues
	__eod__
	exit 0

}

version() {
	cat <<-__eod__
		${ME} version $VERSION
		
		Copyright (C) 2016  www.coolparadox.com
		License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
		This program comes with ABSOLUTELY NO WARRANTY.
		This is free software, and you are welcome to redistribute it
		under certain conditions; see License for details.
	__eod__
	exit 0
}

fail() {
	echo "${ME}: error: $*" 1>&2
	exit 1
}

INPUT_FILE='-'
OUTPUT_FILE=''
LABEL=$DEFAULT_LABEL
while test $# -gt 0 ; do
	OPT=$1
	case $OPT in

	-h|--help) help ;;

	-v|--version) version ;;

	-l|--label)
		shift
		test $# -gt 0 || fail "missing label"
		LABEL=$1
		shift
		;;

	-l=*)
		LABEL=${OPT#-l=}
		shift
		;;

	--label=*)
		LABEL=${OPT#--label=}
		shift
		;;

	-o|--output)
		shift
		test $# -gt 0 || fail "missing output file name"
		OUTPUT_FILE=$1
		shift
		;;

	-o=*)
		OUTPUT_FILE=${OPT#-o=}
		shift
		;;

	--output=*)
		OUTPUT_FILE=${OPT#--output=}
		shift
		;;

	-) break ;;

	-*) usage ;;

	*) break ;;

	esac
done
test $# -eq 0 || {
	INPUT_FILE="$1"
	test -n "$INPUT_FILE" || fail "missing input file"
	shift
}
test $# -eq 0 || fail "too many arguments"

test "$INPUT_FILE" != '-' || INPUT_FILE=''
test -z "$INPUT_FILE" -o -n "$OUTPUT_FILE" || {
	OUTPUT_DIR=$( dirname "$INPUT_FILE" )
	OUTPUT_BASE=$( basename "$INPUT_FILE" )
	OUTPUT_NAME=${OUTPUT_BASE/.*/}
	OUTPUT_EXTENSION=${OUTPUT_BASE/*\./.}
	test "$OUTPUT_NAME" != "$OUTPUT_EXTENSION" || OUTPUT_EXTENSION=''
	OUTPUT_FILE="$OUTPUT_DIR/${OUTPUT_NAME}${OUT_SUFFIX}${OUTPUT_EXTENSION}"
}
test "$OUTPUT_FILE" != '-' || OUTPUT_FILE=''
RM_IN=''
test -n "$INPUT_FILE" || {
	INPUT_FILE=$( mktemp )
	RM_IN="rm -f $INPUT_FILE"
	cat 1>$INPUT_FILE
}
RM_OUT=''
CAT_OUT=''
test -n "$OUTPUT_FILE" || {
	OUTPUT_FILE=$( mktemp )
	RM_OUT="rm -f $OUTPUT_FILE"
	CAT_OUT="cat $OUTPUT_FILE"
}

# Generate watermark unit

SOURCE_W=$( identify -format '%w' $INPUT_FILE )
SOURCE_H=$( identify -format '%h' $INPUT_FILE )
FONT=$DEFAULT_FONT
POINTSIZE_MIN=20
POINTSIZE=$((SOURCE_H / 30))
test $POINTSIZE -ge $POINTSIZE_MIN || POINTSIZE=$POINTSIZE_MIN
TILE_W=$((100*POINTSIZE))
TILE_H=$((10*POINTSIZE))
TILE_FGND_FILE=$( mktemp )
LABEL=$( echo -e "$LABEL" )

# Label image at bottom

convert \
	$INPUT_FILE \
	-font $FONT \
	-pointsize $POINTSIZE \
	-draw \
		"gravity south \
		fill black  text 0,12 '${LABEL}' \
		fill white  text 1,11 '${LABEL}' " \
	$OUTPUT_FILE
$RM_IN
$CAT_OUT
$RM_OUT

