#!/bin/bash

set -e

INPUT_FILE='sample.jpg'

SOURCE_W=$( identify -format '%w' $INPUT_FILE )
SOURCE_H=$( identify -format '%h' $INPUT_FILE )

# Generate tile unit

LABEL='www.
coolparadox
.com'
FONT='Arial'
POINTSIZE_MIN=20
POINTSIZE=$((SOURCE_H / 30))
test $POINTSIZE -ge $POINTSIZE_MIN || POINTSIZE=$POINTSIZE_MIN
TILE_W=$((100*POINTSIZE))
TILE_H=$((10*POINTSIZE))
TILE_FGND_FILE=$( mktemp XXXXXXXXXX.png )
convert \
	-size ${TILE_W}x${TILE_H} \
	xc:grey30 \
	-font "$FONT" \
	-pointsize $POINTSIZE \
	-gravity center \
	-draw "fill grey70 text 0,0 '${LABEL}'" \
	$TILE_FGND_FILE
TILE_MASK_FILE=$( mktemp XXXXXXXXXX.png )
convert \
	-size ${TILE_W}x${TILE_H} \
	xc:black \
	-font "$FONT" \
	-pointsize $POINTSIZE \
	-gravity center \
	-draw \
		"fill white text 1,1 '${LABEL}' \
		text 0,0 '${LABEL}' \
		fill black text -1,-1 '${LABEL}'" \
	+matte \
	$TILE_MASK_FILE
TILE_FILE=$( mktemp XXXXXXXXXX.png )
composite -compose CopyOpacity $TILE_MASK_FILE $TILE_FGND_FILE $TILE_FILE
rm -r $TILE_FGND_FILE $TILE_MASK_FILE
mogrify -trim +repage $TILE_FILE
TILE_W=$( identify -format '%w' $TILE_FILE )
TILE_H=$( identify -format '%h' $TILE_FILE )

# Generate watermark background

MARK_FILE=$( mktemp XXXXXXXXXX.png )
convert \
	$TILE_FILE \
	-set \
		option:distort:viewport \
		${SOURCE_W}x${SOURCE_H}-$((SOURCE_W/2-TILE_W/2))-$((SOURCE_H/2-TILE_H/2)) \
	-background transparent \
	-virtual-pixel CheckerTile \
	-distort SRT 0 \
	+repage \
	$MARK_FILE
rm -f $TILE_FILE

# Compose watermarked image

composite \
	-dissolve 20% \
	-gravity center \
	$MARK_FILE $INPUT_FILE \
	result.jpg
rm -f $MARK_FILE

